// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkMJCEeMmBo84MqOE5Jg0AB3qQJKe4rCQ',
    appId: '1:231460986117:web:123d3890f87c396a296b6c',
    messagingSenderId: '231460986117',
    projectId: 'furyu-hackathon-hiyokogumi',
    authDomain: 'furyu-hackathon-hiyokogumi.firebaseapp.com',
    storageBucket: 'furyu-hackathon-hiyokogumi.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVeDA-F_rkBidu2kt0OWzFcdtXHivskuQ',
    appId: '1:231460986117:android:3356304bc1f12874296b6c',
    messagingSenderId: '231460986117',
    projectId: 'furyu-hackathon-hiyokogumi',
    storageBucket: 'furyu-hackathon-hiyokogumi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm0N5GUEzWOA5oAvziDRDL1Uzm2NuszrE',
    appId: '1:231460986117:ios:5cc2a64590b65962296b6c',
    messagingSenderId: '231460986117',
    projectId: 'furyu-hackathon-hiyokogumi',
    storageBucket: 'furyu-hackathon-hiyokogumi.appspot.com',
    iosBundleId: 'com.example.furyuHackathon2024Hiyokogumi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm0N5GUEzWOA5oAvziDRDL1Uzm2NuszrE',
    appId: '1:231460986117:ios:39b36968f770bfc7296b6c',
    messagingSenderId: '231460986117',
    projectId: 'furyu-hackathon-hiyokogumi',
    storageBucket: 'furyu-hackathon-hiyokogumi.appspot.com',
    iosBundleId: 'com.example.furyuHackathon2024Hiyokogumi.RunnerTests',
  );
}
